"use client";

import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
export function DownloadSummaryButton({
  title,
  summary_text,
  file_name,
  created_at,
  original_file_url,
}: {
  title: string;
  summary_text: string;
  file_name: string;
  created_at: string;
  original_file_url: string;
}) {
  const handleDownload = () => {
    const summaryContent = `
# ${title}
Generated Summary
Generated on: ${new Date(created_at).toLocaleDateString("en-US")}

${summary_text}

Original file: [${file_name}](${original_file_url})
Generated by PageSync AI
    `;
    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-zA-Z0-9]/gi, "_")}.txt`;
    document.body.appendChild(link); // Append link to the body
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url); // Clean up the URL object in browser memory
  };
  return (
    <>
      <Button
        size="sm"
        className="h-8 px-3 bg-rose-100 text-rose-600 hover:bg-rose-50 hover:text-rose-700 "
        variant="outline"
        onClick={handleDownload}
      >
        <Download className="h-4 w-4 mr-1" />
        Download Summary
      </Button>
    </>
  );
}
